// CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES'

// PICTURES
export const GET_PICTURES = 'GET_PICTURES'
export const GET_PICTURE = 'GET_PICTURE'
export const ADD_PICTURE = 'ADD_PICTURE'
export const EDIT_PICTURE = 'EDIT_PICTURE'
export const REMOVE_PICTURE = 'REMOVE_PICTURE'